<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="domain" nsURI="http://no/tdt4250/project/pokeDex/model" nsPrefix="no.tdt4250.project.pokeDex.model">
  <eClassifiers xsi:type="ecore:EClass" name="Domain">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="kingdoms" upperBound="-1"
        eType="#//Kingdom" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Kingdom">
    <eStructuralFeatures xsi:type="ecore:EReference" name="phyla" upperBound="-1"
        eType="#//Phylum" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="#//Kingdoms"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Phylum">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classes" upperBound="-1"
        eType="#//Class" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="#//Phlya"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Class">
    <eStructuralFeatures xsi:type="ecore:EReference" name="genera" upperBound="-1"
        eType="#//Genus" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="#//Classes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Genus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="species" upperBound="-1"
        eType="#//Species" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="habitat" eType="#//Habitats"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sameAnatomy" upperBound="-1"
        eType="#//Genus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anatomy" lowerBound="1"
        eType="#//Anatomy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Species">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="evolvesTo" eType="#//Species"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="evolvesFrom" eType="#//Species"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="icon" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Kingdoms">
    <eLiterals name="Plantae"/>
    <eLiterals name="Animalia" value="1"/>
    <eLiterals name="Mineralia" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Phlya">
    <eLiterals name="Chordates"/>
    <eLiterals name="Arthropods" value="1"/>
    <eLiterals name="Vertebrate" value="2"/>
    <eLiterals name="Angiospermophyta" value="3"/>
    <eLiterals name="Metamorphic" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Classes">
    <eLiterals name="Bird"/>
    <eLiterals name="Fish" value="1"/>
    <eLiterals name="Dragon" value="2"/>
    <eLiterals name="Fairy" value="3"/>
    <eLiterals name="Mammal" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Habitats">
    <eLiterals name="Cave"/>
    <eLiterals name="Forest" value="1"/>
    <eLiterals name="Grassland" value="2"/>
    <eLiterals name="Mountain" value="3"/>
    <eLiterals name="Rare" value="4"/>
    <eLiterals name="RoughTerrain" value="5"/>
    <eLiterals name="Sea" value="6"/>
    <eLiterals name="Urban" value="7"/>
    <eLiterals name="WatersEdge" value="8"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Anatomy">
    <eLiterals name="Ball"/>
    <eLiterals name="Fish" value="1"/>
    <eLiterals name="Squiggle" value="2"/>
    <eLiterals name="Arms" value="3"/>
    <eLiterals name="Blob" value="4"/>
    <eLiterals name="Upright" value="5"/>
    <eLiterals name="Legs" value="6"/>
    <eLiterals name="Quadruped" value="7"/>
    <eLiterals name="Wings" value="8" literal="Wings"/>
    <eLiterals name="Tentacles" value="9"/>
    <eLiterals name="Heads" value="10"/>
    <eLiterals name="Humanoid" value="11"/>
    <eLiterals name="BugWings" value="12"/>
    <eLiterals name="Armor" value="13"/>
  </eClassifiers>
</ecore:EPackage>
